### ISSUE TITLE
Gift abuse bug

### ISSUE THREAD

**Issue by Plastisheep** [Luke100000/minecraft-comes-alive#393] opened 2022-09-12 19:26 UTC
If you are married to someone you can take a valuable out of their inventory and regift it to them to get unlimited hearts with them.

**Comment by CDAGaming** [comment] 2022-09-12 20:35
I'm willing to class this as intended, since the only ways to fix this involve somehow tracking an item based on nbt, which is complex and horrendus, as well as the fact that after gifting the same thing multiple times, villagers dont tend to react well (As in they dont like it, so there's already a system to nerf this a bit)

Closing as such, but @Luke100000 can re-open if they wanna deal with it in 7.4

**Closed as completed by CDAGaming** 2022-09-12 20:35 UTC

**Comment by Canriii** [comment] 2024-12-31 01:46
Here's a possible solution to this;
When gifting an item to a family member who's inventory you can manage, there can be a customizable cooldown for how long you can wait before the item can be taken out, while items given through the inventory can be managed whenever.

You can also add a tag to the item that stores the info of how many hearts were gifted while being given the item, and remove the hearts when the item is taken.
