### ISSUE TITLE
My base is considered an Inn and always becomes one

### ISSUE THREAD

**Issue by KSSTEA** [Luke100000/minecraft-comes-alive#279] opened 2022-07-05 18:28 UTC
My base is considered an Inn and I don't want that, I've used the blueprint to remove the building but it doesn't work, it always comes back as an Inn

**Comment by CDAGaming** [comment] 2022-08-21 18:20
Closing as intended, please refer to the blueprint requirements of an inn. If you dont want it to be considered an inn either remove one of the key items for an inn, or use `/mca-admin forcebuildingType` to force it to be something else.

**Closed as completed by CDAGaming** 2022-08-21 18:20 UTC
