### ISSUE TITLE
Falling Out of the World After Generating a New World

### ISSUE THREAD

**Issue by TheButterbrotMan** [Luke100000/minecraft-comes-alive#256] opened 2022-06-20 23:14 UTC
When I generate a new world under the Deathdusk modpack, I found myself falling through the world terrain and dying in the void as a result. Although I keep my stuff the first time, when I update the modpack and log back into my world, I also fall through the blocks below me and die in the void, losing all of my items in the process. I also found out that the bug occurs when I load up a survival world; I don't fall through the world while starting a creative world.

Disabling "LaunchIntoDestiny" fixed the problem.

**Comment by Luke100000** [comment] 2022-06-21 07:24
Did this happen in 7.3.3 or before?

**Comment by TheButterbrotMan** [comment] 2022-06-21 12:28
7.3.2 and before

**Comment by Luke100000** [comment] 2022-06-21 13:05
Interesting. The limit the villager can spawn is 1. Which, since the cave update, is 64 blocks above the limit. If the world is not loaded yet, the player should not be able to move. I can not imagine why the player could fall through.

Are there alternative ways to get Deathdusk? I do not have access to windows right now and curseforge doesn't like linux last time I checked.

**Comment by TheButterbrotMan** [comment] 2022-06-21 13:07
> Interesting. The limit the villager can spawn is 1. Which, since the cave update, is 64 blocks above the limit. If the world is not loaded yet, the player should not be able to move. I can not imagine why the player could fall through.

I think curseforge published a linux version, also i heard ATLauncher works.

**Comment by TheButterbrotMan** [comment] 2022-06-21 14:15
It seems like MCA Destiny menu is closing itself.

**Comment by Luke100000** [comment] 2022-06-21 14:17
wut? At what screen? Any correlation with other actions?

**Comment by TheButterbrotMan** [comment] 2022-06-21 14:23
No. I am just creating a new world. MCA Destiny screen loads up. And then it closes itself and I fall trough world. Lol.

**Comment by Luke100000** [comment] 2022-06-21 14:29
Without you clicking anything? Do you stay at the model and gender selections creen?

**Comment by TheButterbrotMan** [comment] 2022-06-21 14:33
> Without you clicking anything? Do you stay at the model and gender selections creen?

Yes. I stay at name select screen. Doing nothing. Just watching what the game does.

**Comment by Luke100000** [comment] 2022-06-21 14:42
Who closes my screen! XD I will try to reproduce that error with your Modpack

**Comment by TheButterbrotMan** [comment] 2022-06-21 14:44
Idk tbh.

Maybe https://www.curseforge.com/minecraft/mc-mods/dynamic-crosshair-compat?

**Comment by TheButterbrotMan** [comment] 2022-06-21 14:45
Here is the changelog of this update:
https://www.curseforge.com/minecraft/modpacks/deathdusk/files/3835001

**Comment by TheButterbrotMan** [comment] 2022-07-04 22:44
https://www.curseforge.com/minecraft/mc-mods/fastload

"We do this in a better, safer way by simply dialing down the number of chunks required to load before 441 initialises. This is fairly self-explanatory! To make world loading faster, we integrated yet another 'unstable' mod, Forcecloseloadingscreen. Like ksyxis, it also issues a firm warning of instability. How did we improve this? Just by initialising the pre-renderer earlier in the world initiation phase as well as preventing the 'Pause Menu' activating when not focused on the window until the real renderer initialised. We also make it cancel only when the player spawns, to avoid issues where the player spawns in the wrong locations with incorrect playerdata. Thus, fixing the bugs that mods brings in too! There's your technical explanation!"

**Comment by Luke100000** [comment] 2022-07-08 14:07
In 7.3.5 I used the "vanilla" way of teleporting. It didn't fix the issue for me, I still seem to fall through the world for around a second, but maybe it's only visual this time

**Comment by CDAGaming** [comment] 2022-07-21 20:39
@Luke100000 verify for 7.3.9

**Comment by CDAGaming** [comment] 2022-08-21 17:04
Closed as assumed resolved in accordance to #237 also relating to a similar issue, and 7.3.5+ being as vanilla as we can make it.

**Closed as completed by CDAGaming** 2022-08-21 17:04 UTC
Labels: bug, mod compatibility
