### ISSUE TITLE
[7.3.5+] Mod crashes game when shaders are enabled

### ISSUE THREAD

**Issue by seancrain** [Luke100000/minecraft-comes-alive#299] opened 2022-07-16 01:16 UTC
A change was introduced in 7.3.5 that causes the game to crash upon loading a world when shaders are enabled. The game loads to a screen with a triangular shape, then it crashes.

[https://www.nosiphus.com/minecraft/crash-reports/crash-2022-07-15_20.06.13-client.txt](https://www.nosiphus.com/minecraft/crash-reports/crash-2022-07-15_20.06.13-client.txt)

The issue is not present in 7.3.4, so I have downgraded to that for the time being.

Forge: 40.1.54 (OptiFine has issues with the current release, so test against this build)
OptiFine: 1.18.2_HD_U_H7
Shader: Complementary Shaders 4.5.1

Also tested against Fabric 0.14.8 and Iris on Minecraft 1.19.1, similar behavior

**Comment by Luke100000** [comment] 2022-07-16 12:28
Optifine being funky again, I will take a look at this

**Comment by seancrain** [comment] 2022-08-03 02:04
So, I can give some updated context for this. This issue is occurring against Iris on 1.19 as well, but the thing is that the issue doesn't appear on a consistent basis. I have used Complementary Shaders for my testing.

It has materialized on some first-run singleplayer worlds, and it has worked fine on others. I have loaded up two packs with the exact same set of mods. It'll work the first time, but after closing down the pack, it will crash on the second time, or some combination. As I said, it is not consistent...with one exception.

This error is consistent if you attempt to join a multiplayer server.

**Comment by CDAGaming** [comment] 2022-08-25 15:02
This issue should be fixed in newer optifine releases, please reopen if still present in the latest mca version

**Closed as completed by CDAGaming** 2022-08-25 15:02 UTC
Labels: mod compatibility

**Comment by seancrain** [comment] 2022-08-31 14:39
Nope, it most certainly isn't fixed. It keeps loading to this:
![What Happens](https://user-images.githubusercontent.com/38871906/187705484-e6ec7d23-0f95-4a5d-9c52-5edc0abf9fee.png)
It seems to be able to figure out the in-game time of day, because usually it's on top of a bright background, but this time it was dark. Regardless, this issue is very much still present. I have updated to 7.3.20 and OptiFine 1.18.2 H9 pre1. "Telkit IV" is a pack maintained by me. It is also present in my "NosiFabric" pack which is Fabric-based on 1.19.2, using Iris 1.2.8.

Please reopen as this is not fixed.

**Comment by CDAGaming** [comment] 2022-08-31 14:43
@seancrain Send us a link to your pack, and we'll reproduce it from there

**Comment by seancrain** [comment] 2022-08-31 14:53
My packs use MultiMC and Packwiz, here are the installation instructions:
[https://modpack.nosiphus.com/installation-instructions](https://modpack.nosiphus.com/installation-instructions)
The packs in question are Telkit IV and NosiFabric. I have not updated Telkit III, which is 1.16.5-based, to the latest MCA Reborn build yet, but I suspect it will likely happen there too if I do.
I will keep both the Telkit IV and NosiFabric servers up so you can see what happens there. I cannot for the life of me figure out what is causing the crash, hopefully you guys can.

**Comment by Luke100000** [comment] 2022-08-31 14:56
Notice that I just fixed a very similar error, maybe try 7.3.21.

**Comment by Luke100000** [comment] 2022-08-31 14:56
ba683841ef7d00ae4aec72d951ed14df8f909cf0

**Comment by CDAGaming** [comment] 2022-08-31 14:56
It isnt up yet for 1.16.5 Luke, but given whats going on I'll push a RC for 1.16.5 and 1.17.1 as well

**Comment by seancrain** [comment] 2022-08-31 14:57
I'll have to wait for those builds to hit Modrinth, but I will update as soon as they do

**Comment by seancrain** [comment] 2022-08-31 15:10
Disabling the villager player model caused the crash to return because it wasn't happening before I set the configuration settings. I think that's probably what is happening.

**Comment by Luke100000** [comment] 2022-08-31 15:13
Then it's the issue I link!

**Comment by seancrain** [comment] 2022-08-31 15:13
Then that clears it up. Do you have an ETA on when those builds will be out for 1.16, 1.18, and 1.19?

**Comment by Luke100000** [comment] 2022-08-31 15:14
sometime today, 7.3.21+rc.1

**Comment by seancrain** [comment] 2022-08-31 15:15
Alright, I'll be waiting. I'll have to delete the server map and WorldEdit everything back in, because I don't think existing villages will be overwritten with MCA villagers (correct me if I'm wrong), but I'm glad I can finally play this mod again!

**Comment by Luke100000** [comment] 2022-08-31 15:20
Since you are the 100th person asking for villager conversion after world gen, I will add this as a command :)

**Comment by seancrain** [comment] 2022-08-31 15:20
thank you

**Comment by CDAGaming** [comment] 2022-08-31 17:17
@seancrain 7.3.21-rc1 is now being released as we speak, please test on that version and let us know if things are resolved on your end.

**Comment by seancrain** [comment] 2022-08-31 17:57
It loaded with no crashes. Thanks, guys, issue has been resolved.
