### ISSUE TITLE
[Question] Disable spawn book.

### ISSUE THREAD

**Issue by Taknax** [Luke100000/minecraft-comes-alive#319] opened 2022-07-30 11:07 UTC
Is the spawn book disalable?
If not a config to disable the spawning books would be nice.

**Comment by CDAGaming** [comment] 2022-07-30 20:28
Closed as intended functionality. The book in question comes from an acheivement upon entering a village or seeing you entered one before. If you wish to disable it, simply remove it from the advancements rewards in `root.json` in `data/mca/advancements`

**Closed as completed by CDAGaming** 2022-07-30 20:28 UTC
