### ISSUE TITLE
Injection Failure on mohist

### ISSUE THREAD

**Issue by FlyoC** [Luke100000/minecraft-comes-alive#439] opened 2022-10-22 22:27 UTC
Hi, i have a server with minecraft comes alive and architectury and every time i open the server it crashes
Version of MCA: 1.16.5-7.3.19
version of Architectury: 1.32.66

```Crash Log:
[22:23:26 FATAL]: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER
[22:23:26 WARN]: Error loading class: net/minecraft/client/entity/player/ClientPlayerEntity (java.lang.RuntimeException: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER)
[22:23:26 WARN]: @Mixin target net.minecraft.client.entity.player.ClientPlayerEntity was not found ars_nouveau.mixins.json:ClientElytraMixin
[22:23:30 INFO]: [org.slf4j.helpers.Util:report:128]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[22:23:30 INFO]: [org.slf4j.helpers.Util:report:128]: SLF4J: Defaulting to no-operation (NOP) logger implementation
[22:23:30 INFO]: [org.slf4j.helpers.Util:report:128]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[22:23:34 INFO]: Mixing MixinContainer from theft.mixins.json into net.minecraft.inventory.container.Container
[22:23:34 FATAL]: Mixin apply failed forge-mca.mixin.json:MixinAbstractFurnaceBlockEntity -> net.minecraft.tileentity.AbstractFurnaceTileEntity: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on onDropExperience could not find any targets matching 'Lnet/minecraft/tileentity/AbstractFurnaceTileEntity;func_235645_d_(Lnet/minecraft/entity/player/PlayerEntity;)V' in net.minecraft.tileentity.AbstractFurnaceTileEntity. Using refmap forge-minecraft-comes-alive-common-refmap.json [PREINJECT Applicator Phase -> forge-mca.mixin.json:MixinAbstractFurnaceBlockEntity -> Prepare Injections ->  -> handler$zei000$onDropExperience(Lnet/minecraft/entity/player/PlayerEntity;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on onDropExperience could not find any targets matching 'Lnet/minecraft/tileentity/AbstractFurnaceTileEntity;func_235645_d_(Lnet/minecraft/entity/player/PlayerEntity;)V' in net.minecraft.tileentity.AbstractFurnaceTileEntity. Using refmap forge-minecraft-comes-alive-common-refmap.json [PREINJECT Applicator Phase -> forge-mca.mixin.json:MixinAbstractFurnaceBlockEntity -> Prepare Injections ->  -> handler$zei000$onDropExperience(Lnet/minecraft/entity/player/PlayerEntity;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at jdk.internal.reflect.GeneratedConstructorAccessor41.newInstance(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1311) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) ~[modlauncher-8.1.3.jar:8.1.3+8.1.3+main-8.1.x.c94d18ec]
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.minecraft.block.Blocks.<clinit>(Blocks.java:198) ~[?:?]
        at net.minecraft.world.gen.surfacebuilders.SurfaceBuilder.<clinit>(SurfaceBuilder.java:12) ~[?:?]
        at net.minecraft.world.gen.surfacebuilders.ConfiguredSurfaceBuilders.<clinit>(SourceFile:11) ~[?:?]
        at net.minecraft.util.registry.WorldGenRegistries.func_243674_g(WorldGenRegistries.java:34) ~[?:?]
        at net.minecraft.util.registry.WorldGenRegistries.lambda$static$8(WorldGenRegistries.java:90) ~[?:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
        at net.minecraft.util.registry.WorldGenRegistries.<clinit>(WorldGenRegistries.java:89) ~[?:?]
        at net.minecraft.util.registry.Registry.<clinit>(Registry.java:465) ~[?:?]
        at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:41) ~[?:?]
        at net.minecraft.server.Main.main(Main.java:142) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:37) ~[server.jar:36.2]
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) ~[modlauncher-8.1.3.jar:?]
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:105) ~[server.jar:?]
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:102) ~[server.jar:?]
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:86) ~[server.jar:?]
Exception in thread "main" [22:23:34 INFO]: [java.lang.ThreadGroup:uncaughtException:1077]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[22:23:34 INFO]: [java.lang.ThreadGroup:uncaughtException:1077]:        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[22:23:34 INFO]: [java.lang.ThreadGroup:uncaughtException:1077]:        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[22:23:34 INFO]: [java.lang.ThreadGroup:uncaughtException:1077]:        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[22:23:34 INFO]: [java.lang.ThreadGroup:uncaughtException:1077]:        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[22:23:34 INFO]: [java.lang.ThreadGroup:uncaughtException:1077]:        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[22:23:34 INFO]: [java.lang.ThreadGroup:uncaughtException:1077]:        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:105)
[22:23:34 INFO]: [java.lang.ThreadGroup:uncaughtException:1077]:        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:102)
[22:23:34 INFO]: [java.lang.ThreadGroup:uncaughtException:1077]:        at net.minecraftforge.server.ServerMain.main(ServerMain.java:86)
[22:23:34 INFO]: [java.lang.ThreadGroup:uncaughtException:1086]: Caused by: java.lang.reflect.InvocationTargetException
[22:23:34 INFO]: [java.lang.ThreadGroup:uncaughtException:1086]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:23:34 INFO]: [java.lang.ThreadGroup:uncaughtException:1086]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[22:23:34 INFO]: [java.lang.ThreadGroup:uncaughtException:1086]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:23:34 INFO]: [java.lang.ThreadGroup:uncaughtException:1086]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[22:23:34 INFO]: [java.lang.ThreadGroup:uncaughtException:1086]:        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:37)
[22:23:34 INFO]: [java.lang.ThreadGroup:uncaughtException:1086]:        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[22:23:34 INFO]: [java.lang.ThreadGroup:uncaughtException:1086]:        ... 7 more
[22:23:34 INFO]: [java.lang.Throwable:printStackTrace:659]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[22:23:34 INFO]: [java.lang.Throwable:printStackTrace:659]:     at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[22:23:34 INFO]: [java.lang.Throwable:printStackTrace:659]:     at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
[22:23:34 INFO]: [java.lang.Throwable:printStackTrace:659]:     at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
[22:23:34 INFO]: [java.lang.Throwable:printStackTrace:659]:     at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
[22:23:34 INFO]: [java.lang.Throwable:printStackTrace:659]:     at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[22:23:34 INFO]: [java.lang.Throwable:printStackTrace:659]:     at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[22:23:34 INFO]: [java.lang.Throwable:printStackTrace:659]:     at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[22:23:34 INFO]: [java.lang.Throwable:printStackTrace:659]:     at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[22:23:34 INFO]: [java.lang.Throwable:printStackTrace:659]:     at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[22:23:34 INFO]: [java.lang.Throwable:printStackTrace:659]:     at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[22:23:34 INFO]: [java.lang.Throwable:printStackTrace:659]:     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[22:23:34 INFO]: [java.lang.Throwable:printStackTrace:659]:     at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[22:23:34 INFO]: [java.lang.Throwable:printStackTrace:659]:     at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
[22:23:34 INFO]: [java.lang.Throwable:printStackTrace:659]:     at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138)
[22:23:34 INFO]: [java.lang.Throwable:printStackTrace:659]:     at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[22:23:34 INFO]: [java.lang.Throwable:printStackTrace:659]:     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[22:23:34 INFO]: [java.lang.Throwable:printStackTrace:659]:     at net.minecraft.block.Blocks.<clinit>(Blocks.java:198)
[22:23:34 INFO]: [java.lang.Throwable:printStackTrace:659]:     at net.minecraft.world.gen.surfacebuilders.SurfaceBuilder.<clinit>(SurfaceBuilder.java:12)
[22:23:34 INFO]: [java.lang.Throwable:printStackTrace:659]:     at net.minecraft.world.gen.surfacebuilders.ConfiguredSurfaceBuilders.<clinit>(SourceFile:11)
[22:23:34 INFO]: [java.lang.Throwable:printStackTrace:659]:     at net.minecraft.util.registry.WorldGenRegistries.func_243674_g(WorldGenRegistries.java:34)
[22:23:34 INFO]: [java.lang.Throwable:printStackTrace:659]:     at net.minecraft.util.registry.WorldGenRegistries.lambda$static$8(WorldGenRegistries.java:90)
[22:23:34 INFO]: [java.lang.Throwable:printStackTrace:659]:     at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
[22:23:34 INFO]: [java.lang.Throwable:printStackTrace:659]:     at net.minecraft.util.registry.WorldGenRegistries.<clinit>(WorldGenRegistries.java:89)
[22:23:34 INFO]: [java.lang.Throwable:printStackTrace:659]:     at net.minecraft.util.registry.Registry.<clinit>(Registry.java:465)
[22:23:34 INFO]: [java.lang.Throwable:printStackTrace:659]:     at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:41)
[22:23:34 INFO]: [java.lang.Throwable:printStackTrace:659]:     at net.minecraft.server.Main.main(Main.java:142)
[22:23:34 INFO]: [java.lang.Throwable:printStackTrace:659]:     ... 13 more
[22:23:34 INFO]: [java.lang.Throwable:printStackTrace:682]: Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [forge-mca.mixin.json:MixinAbstractFurnaceBlockEntity] from phase [DEFAULT] in config [forge-mca.mixin.json] FAILED during APPLY
[22:23:34 INFO]: [java.lang.Throwable:printStackTrace:682]:     at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:636)
[22:23:34 INFO]: [java.lang.Throwable:printStackTrace:682]:     at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:588)
[22:23:34 INFO]: [java.lang.Throwable:printStackTrace:682]:     at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
[22:23:34 INFO]: [java.lang.Throwable:printStackTrace:682]:     ... 38 more
```

**Comment by Luke100000** [comment] 2022-10-24 09:04
~~Do you use Catserver by any chance?~~
Should have read the title too. In any case, it is most likely a indirect duplicate of this issue here: #378
Both implement Bukkit API, both fail at this damn mixin.

**Closed as completed** 2022-10-24 09:12 UTC
Labels: bukkit
