### ISSUE TITLE
Suggestion: Hardcore Functionality

### ISSUE THREAD

**Issue by Jigbashmop** [Luke100000/minecraft-comes-alive#155] opened 2022-04-06 00:26 UTC
The original MCA (at one point) had a unique feature that I found really creative and interesting. Basically, if you died in Hardcore you would have the option to continue playing as one of your children. I'm not sure why it was removed, but I'm wondering if you'd be able to bring this back in the new version. It has amazing RP potential and I love the idea of playing as a scion, picking up your parent's sword to avenge them/follow in their footsteps.

Now I'm envisioning an aging mechanic where villagers (or even players) might grow weaker and die as they approach a certain age, allowing for generations to come and go. Though I think that might be a bit outside the scope of the mod, as cool as it would be.

**Comment by Luke100000** [comment] 2022-04-06 12:23
Duplicate of #135, will return. Second suggestion is not out of scope but would be disabled by default and requires quite some time to implement, so its on the bottom of the todo for now :)

**Closed as completed by Luke100000** 2022-04-06 12:23 UTC
Labels: duplicate, enhancement
