### ISSUE TITLE
Suggest:compatible epic fight

### ISSUE THREAD

**Issue by ghost** [Luke100000/minecraft-comes-alive#349] opened 2022-08-20 06:53 UTC
Battle Mode, model conflict
Recommended Compatible
![2022-08-20_14 40 43](https://user-images.githubusercontent.com/83486178/185733094-8f59b116-5707-4472-9470-3a12da7dfa93.png)

**Comment by CDAGaming** [comment] 2022-08-21 18:24
Duplicate of #203

**Closed as completed by CDAGaming** 2022-08-21 18:24 UTC
Labels: duplicate, mod compatibility
