### ISSUE TITLE
Broken Server Logs

### ISSUE THREAD

**Issue by vampireg0th** [Luke100000/minecraft-comes-alive#709] opened 2023-07-17 19:01 UTC
**Describe the bug**
Minecraft Comes Alive breaks non-minecraft (Ledger & Graves) commands and makes them unable to translate (?)

**To Reproduce**
1. Have Ledger and Minecraft Comes Alive on a Fabric server
2. Type /lg inspect
3. Click chest or block

**Screenshots**
![image](https://github.com/Luke100000/minecraft-comes-alive/assets/106853545/5d539233-f952-423d-960b-6d414b10e5d2)
![image](https://github.com/Luke100000/minecraft-comes-alive/assets/106853545/21990c5d-6157-4106-8fb5-0d036cfbc8e9)

**Version**
minecraft comes alive 7.5.3, 1.20.1, Fabric 0.14.21

**Latest.log**
[Server Logs.txt](https://github.com/Luke100000/minecraft-comes-alive/files/12073027/Server.Logs.txt)

**Comment by Luke100000** [comment] 2023-07-17 19:53
duplicate of #694

**Closed as completed by Luke100000** 2023-07-17 19:53 UTC
Labels: bug
