### ISSUE TITLE
Reset House - Ability to work around housing bug

### ISSUE THREAD

**Issue by ncottrill** [Luke100000/minecraft-comes-alive#558] opened 2023-02-03 18:52 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when trying to place villagers in a home. The villagers don't seem to stay in the home that I want them to live in. I'm not sure why. 

**Describe the solution you'd like**
Maybe the simplest approach would be a button that clears the house of any occupants. "Remove all occupants" Or "Reset House" button on the map UI and in the "advanced" section. The beds would still be recognized, but all the occupants would be removed. 

Once the house is reset (cleared of all occupants), then I could assign the villagers I want to live there.

**Describe alternatives you've considered**
The best solution would be to make any villager housing placements that the player assigns to a house stay static (unchanged) until the player puts the villager in another house or the villager dies. But that might be more complicated coding that simply a button to clear the house occupants.

**Additional context**
I am happy to elaborate if needed - just reply to this note.

**Comment by Luke100000** [comment] 2023-02-03 20:26
See my answer in #554, please see if 7.4.1 fixes this. A kick out button sounds nice but I want to avoid any additional features related to homes since the current state is everything but stable already :(

**Comment by ncottrill** [comment] 2023-02-04 04:21
Yeah, I tried 7.4.1 and it wiped out our village maps in the established villages and then would not allow us to add the buildings back (see newest issue I added).

**Comment by Luke100000** [comment] 2023-02-04 18:03
Merged with #561, aside from the wiping, other player confirmed it should work (better) now

**Closed as completed by Luke100000** 2023-02-04 18:03 UTC
Labels: enhancement
