### ISSUE TITLE
Suggestion: Baby delivery adjustment.

### ISSUE THREAD

**Issue by JamesEakk** [Luke100000/minecraft-comes-alive#140] opened 2022-03-26 17:04 UTC
Hi, I love this mod very much, but.

It is rather tiresome to being mayor of a growing town and having to go play hide-and-seek for small babies who aren't even crying in, sometimes, very unlikely places (holes, bushes, water, etc), then have to pick them up on shoulder, suffocate them through 2 blocks high doors before reaching  their parent's room in distant area.

I also usually having "Villager names" mod on which makes baby announcement messages too long to read in rather short time, resulting in sometimes I unknowingly leave them be in the wild and eventually die. 
Even without Villager names mod it is still easy to be missed.

So, my suggestion is to

>  Only having baby born after their mother is woke up in the morning, at their bed.

That would solves all issues above in one go.

Best regards.

**Comment by CDAGaming** [comment] 2022-08-21 18:32
Closing as de-confirmed, since in a technicality a baby can be born at any time, and anywhere.
The `childrenChance` option can be decreased if there are too many occurrences at once though.

**Closed as completed by CDAGaming** 2022-08-21 18:32 UTC
Labels: enhancement
