### ISSUE TITLE
Entering the zombie villager igloo's don't actually spawn zombie villagers.

### ISSUE THREAD

**Issue by ItzASecretBoi** [Luke100000/minecraft-comes-alive#940] opened 2024-05-24 04:03 UTC
![2024-05-23_22 59 47](https://github.com/Luke100000/minecraft-comes-alive/assets/82130468/73a1e799-ceb7-43ab-9078-35e5dea190b2)

I am using a mod that add's more zombie villager igloo variants for each biome, but I'm assuming this can be replicated with the vanilla igloos as well.

Issue is simple instead of having zombie villagers in this structure like vanilla minecraft, they are already normal villagers.

**Comment by frqnny** [comment] 2024-06-25 00:22
This is normal MC behavior. They spawn a villager next to a zombie. Closing this as invalid.
![image](https://github.com/Luke100000/minecraft-comes-alive/assets/45723631/fbcc0a20-fee9-4aa1-888c-d0c4b5918f57)

**Closed as completed by frqnny** 2024-06-25 00:22 UTC
Labels: bug, invalid

**Comment by ItzASecretBoi** [comment] 2024-07-06 18:37
Well my apologies, I was unaware, but there's still no zombie villager though. In the screenshot you can kind of see it's still empty. I might test it with the MCA mod by itself one day.

**Comment by AdmiralGamerz** [comment] 2025-07-15 21:22
> still no zombie villager
 
Little late to this one, but this is most likely caused by either having a separate zombie mod which messes with spawning, or by having the entity culling mod enabled & not allowing MCA zombies in it's config.
