### ISSUE TITLE
Villager's Spouse is dead but married still

### ISSUE THREAD

**Issue by KennaKilla** [Luke100000/minecraft-comes-alive#142] opened 2022-03-31 04:41 UTC
So, I took some villagers from another village took every single one not missing one. but I realized that one of my male villagers was married but could not find his spouse anywhere. I believe she is dead or gone missing. Is there a way of divorcing him from her? Also, I'm playing in peaceful mode so if she was a zombie and got deleted? I was going between peaceful and easy because I build in creative and mobs are annoying but I actually adventure in survival.

**Comment by Luke100000** [comment] 2022-04-06 12:07
Thanks for the hint with peaceful, this could be indeed the cause of disappearance. You can use the villager editor and empty the spouse field to reset.

**Comment by CDAGaming** [comment] 2022-08-21 18:14
Closed as presumed resolved via the fix for #206 
@Luke100000  can correct me if I'm wrong here, but this should be fixed

**Closed as completed by CDAGaming** 2022-08-21 18:14 UTC
Labels: bug
