### ISSUE TITLE
MCA Reborn looks black and white

### ISSUE THREAD

**Issue by Mattyfatty399** [Luke100000/minecraft-comes-alive#420] opened 2022-10-03 00:46 UTC
![Capture1](https://user-images.githubusercontent.com/75187805/193484176-db7b0540-418e-4da3-b175-8186596999f1.JPG)

**Comment by CDAGaming** [comment] 2022-10-03 03:26
Closed as intended. That's how the color blindness trait looks, and can be disabled....by removing the trait from yourself.

**Closed as completed by CDAGaming** 2022-10-03 03:26 UTC
