### ISSUE TITLE
Skin

### ISSUE THREAD

**Issue by Lawasacaca1** [Luke100000/minecraft-comes-alive#347] opened 2022-08-19 05:41 UTC
Does anyone know why I can't choose my skin? 

https://user-images.githubusercontent.com/111557155/185550843-692038bf-dcdd-4dbd-be77-b42b7cc62110.mp4

**Comment by Luke100000** [comment] 2022-08-19 05:55
Does it work outside the editor? It shows you the genetics preview. Since thats very confusing I will add a tooltip under the model or something.

**Comment by Lawasacaca1** [comment] 2022-08-19 06:07
No

**Comment by Lawasacaca1** [comment] 2022-08-19 06:10
> Does it work outside the editor? It shows you the genetics preview. Since thats very confusing I will add a tooltip under the model or something.

It doesn't work, I have tried many things and nothing.

**Comment by Lawasacaca1** [comment] 2022-08-20 02:40
> Does it work outside the editor? It shows you the genetics preview. Since thats very confusing I will add a tooltip under the model or something.

what should I do?

**Comment by Luke100000** [comment] 2022-08-20 08:28
Nothing, from now on I need to find that issue myself to continue. Thanks for reporting!

**Comment by CDAGaming** [comment] 2022-08-21 17:14
@Lawasacaca1 Can you post your log in here (latest.log if you can still reproduce the issue in the latest version)

**Comment by Lawasacaca1** [comment] 2022-08-22 02:32
It's fixed now I can see my skin, but is it normal that I have to put my name?
https://user-images.githubusercontent.com/111557155/185827089-23ded180-6f66-4b7a-bd84-c62489a8d2c2.mp4

**Comment by CDAGaming** [comment] 2022-08-25 15:00
The name can technically be anything, but closing as resolved

**Closed as completed by CDAGaming** 2022-08-25 15:00 UTC
Labels: enhancement, question
